typography_spectrum: 0.35885741375386715
color:
  saturation: 0.9840084514580667
  brandStrength: 0.5994449418503791
  rhythmicContrast: 0.6719130594283342
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  lightness: 0.9762082565575838
layout_spectrum: 0.07450797385536134
author:
  url: 'http://erikjbrown.com'
  name: Erik J. Brown
  email: erikjohnbrown@gmail.com
name: Erik J. Brown
navigation:
  - url: 'https://www.instagram.com/erikjb/'
    name: Follow my Instagram!
    type: external
  - url: 'https://twitter.com/WriterikJB'
    name: Follow Me on Twitter!
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/d0aa1662-5927-44e6-bc67-1001dd86cd2c.jpg
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Erik J. Brown
description: >-
  Writer. Accountant. Badass. Past Life Credits: a saint bernard, a beer-brewing
  monk, a sommelier, and Mrs. O'Leary's Cow.
