typography_spectrum: 0.4251234317198396
color:
  saturation: 0.41670034267008305
  brandStrength: 0.9009709279052913
  rhythmicContrast: 0.03583640092983842
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.6143280547112226
layout_spectrum: 0.6184346203226596
author:
  url: 'http://erikjbrown.com'
  name: Erik J. Brown
  email: erikjohnbrown@gmail.com
name: Erik J. Brown
navigation:
  - id: 058405f9-3bef-4ff9-a0de-f1a40ee65f01
    url: 2016-07-09-about-me.html
    name: About Me
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
