typography_spectrum: 0.2795699
color:
  saturation: 0.05230365
  brandStrength: 0.5693814996629953
  rhythmicContrast: 0.2401434
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  lightness: 0.7461484
layout_spectrum: 1
author:
  url: 'http://erikjbrown.com'
  name: Erik J. Brown
  email: erikjohnbrown@gmail.com
name: Erik J. Brown
navigation: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
